/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TavernRouteImport } from './routes/tavern'
import { Route as ShopRouteImport } from './routes/shop'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as QuestsRouteImport } from './routes/quests'
import { Route as ForgeRouteImport } from './routes/forge'
import { Route as EquipmentRouteImport } from './routes/equipment'
import { Route as ChallengesRouteImport } from './routes/challenges'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ArchivesRouteImport } from './routes/archives'
import { Route as IndexRouteImport } from './routes/index'

const TavernRoute = TavernRouteImport.update({
  id: '/tavern',
  path: '/tavern',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopRoute = ShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const QuestsRoute = QuestsRouteImport.update({
  id: '/quests',
  path: '/quests',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgeRoute = ForgeRouteImport.update({
  id: '/forge',
  path: '/forge',
  getParentRoute: () => rootRouteImport,
} as any)
const EquipmentRoute = EquipmentRouteImport.update({
  id: '/equipment',
  path: '/equipment',
  getParentRoute: () => rootRouteImport,
} as any)
const ChallengesRoute = ChallengesRouteImport.update({
  id: '/challenges',
  path: '/challenges',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ArchivesRoute = ArchivesRouteImport.update({
  id: '/archives',
  path: '/archives',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/archives': typeof ArchivesRoute
  '/auth': typeof AuthRoute
  '/challenges': typeof ChallengesRoute
  '/equipment': typeof EquipmentRoute
  '/forge': typeof ForgeRoute
  '/quests': typeof QuestsRoute
  '/settings': typeof SettingsRoute
  '/shop': typeof ShopRoute
  '/tavern': typeof TavernRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/archives': typeof ArchivesRoute
  '/auth': typeof AuthRoute
  '/challenges': typeof ChallengesRoute
  '/equipment': typeof EquipmentRoute
  '/forge': typeof ForgeRoute
  '/quests': typeof QuestsRoute
  '/settings': typeof SettingsRoute
  '/shop': typeof ShopRoute
  '/tavern': typeof TavernRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/archives': typeof ArchivesRoute
  '/auth': typeof AuthRoute
  '/challenges': typeof ChallengesRoute
  '/equipment': typeof EquipmentRoute
  '/forge': typeof ForgeRoute
  '/quests': typeof QuestsRoute
  '/settings': typeof SettingsRoute
  '/shop': typeof ShopRoute
  '/tavern': typeof TavernRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/archives'
    | '/auth'
    | '/challenges'
    | '/equipment'
    | '/forge'
    | '/quests'
    | '/settings'
    | '/shop'
    | '/tavern'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/archives'
    | '/auth'
    | '/challenges'
    | '/equipment'
    | '/forge'
    | '/quests'
    | '/settings'
    | '/shop'
    | '/tavern'
  id:
    | '__root__'
    | '/'
    | '/archives'
    | '/auth'
    | '/challenges'
    | '/equipment'
    | '/forge'
    | '/quests'
    | '/settings'
    | '/shop'
    | '/tavern'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ArchivesRoute: typeof ArchivesRoute
  AuthRoute: typeof AuthRoute
  ChallengesRoute: typeof ChallengesRoute
  EquipmentRoute: typeof EquipmentRoute
  ForgeRoute: typeof ForgeRoute
  QuestsRoute: typeof QuestsRoute
  SettingsRoute: typeof SettingsRoute
  ShopRoute: typeof ShopRoute
  TavernRoute: typeof TavernRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tavern': {
      id: '/tavern'
      path: '/tavern'
      fullPath: '/tavern'
      preLoaderRoute: typeof TavernRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop': {
      id: '/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof ShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quests': {
      id: '/quests'
      path: '/quests'
      fullPath: '/quests'
      preLoaderRoute: typeof QuestsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forge': {
      id: '/forge'
      path: '/forge'
      fullPath: '/forge'
      preLoaderRoute: typeof ForgeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/equipment': {
      id: '/equipment'
      path: '/equipment'
      fullPath: '/equipment'
      preLoaderRoute: typeof EquipmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/challenges': {
      id: '/challenges'
      path: '/challenges'
      fullPath: '/challenges'
      preLoaderRoute: typeof ChallengesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/archives': {
      id: '/archives'
      path: '/archives'
      fullPath: '/archives'
      preLoaderRoute: typeof ArchivesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ArchivesRoute: ArchivesRoute,
  AuthRoute: AuthRoute,
  ChallengesRoute: ChallengesRoute,
  EquipmentRoute: EquipmentRoute,
  ForgeRoute: ForgeRoute,
  QuestsRoute: QuestsRoute,
  SettingsRoute: SettingsRoute,
  ShopRoute: ShopRoute,
  TavernRoute: TavernRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
