/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TavernRouteImport } from './routes/tavern'
import { Route as QuestsRouteImport } from './routes/quests'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ArchivesRouteImport } from './routes/archives'
import { Route as IndexRouteImport } from './routes/index'

const TavernRoute = TavernRouteImport.update({
  id: '/tavern',
  path: '/tavern',
  getParentRoute: () => rootRouteImport,
} as any)
const QuestsRoute = QuestsRouteImport.update({
  id: '/quests',
  path: '/quests',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ArchivesRoute = ArchivesRouteImport.update({
  id: '/archives',
  path: '/archives',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/archives': typeof ArchivesRoute
  '/auth': typeof AuthRoute
  '/quests': typeof QuestsRoute
  '/tavern': typeof TavernRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/archives': typeof ArchivesRoute
  '/auth': typeof AuthRoute
  '/quests': typeof QuestsRoute
  '/tavern': typeof TavernRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/archives': typeof ArchivesRoute
  '/auth': typeof AuthRoute
  '/quests': typeof QuestsRoute
  '/tavern': typeof TavernRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/archives' | '/auth' | '/quests' | '/tavern'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/archives' | '/auth' | '/quests' | '/tavern'
  id: '__root__' | '/' | '/archives' | '/auth' | '/quests' | '/tavern'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ArchivesRoute: typeof ArchivesRoute
  AuthRoute: typeof AuthRoute
  QuestsRoute: typeof QuestsRoute
  TavernRoute: typeof TavernRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tavern': {
      id: '/tavern'
      path: '/tavern'
      fullPath: '/tavern'
      preLoaderRoute: typeof TavernRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quests': {
      id: '/quests'
      path: '/quests'
      fullPath: '/quests'
      preLoaderRoute: typeof QuestsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/archives': {
      id: '/archives'
      path: '/archives'
      fullPath: '/archives'
      preLoaderRoute: typeof ArchivesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ArchivesRoute: ArchivesRoute,
  AuthRoute: AuthRoute,
  QuestsRoute: QuestsRoute,
  TavernRoute: TavernRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
