-- Mass catalog expansion (gear, consumables, cosmetics, furniture, pets).
-- Equipment uses metadata.slot + bonuses; pet HUD shows generic tinted glyphs unless a bespoke PET_EQUIPMENT_LAYER exists.

INSERT INTO public.shop_items (slug, name, description, category, rarity, price, metadata)
VALUES
  -- commons (equipment)
  ('bulkeq-willow-switch', 'Willow Switch', 'Light reed stick. (+1 STR)', 'equipment', 'common', 78, '{"slot":"weapon","bonuses":{"strength":1}}'),
  ('bulkeq-copper-band', 'Copper Brow Band', 'Simple metal band. (+1 INT)', 'equipment', 'common', 82, '{"slot":"head","bonuses":{"intelligence":1}}'),
  ('bulkeq-moss-pouch-belt', 'Moss Stitch Belt', 'Herb-scented sash. (+1 CON)', 'equipment', 'common', 85, '{"slot":"waist","bonuses":{"constitution":1}}'),
  ('bulkeq-twine-bracers', 'Twine Bracers', 'Rough cord wraps. (+1 STR)', 'equipment', 'common', 80, '{"slot":"hands","bonuses":{"strength":1}}'),
  ('bulkeq-pebble-token', 'Pebble Token', 'River stone charm. (+1 gold% task reward)', 'equipment', 'common', 92, '{"slot":"charm","bonuses":{"gold_bonus_pct":1}}'),
  ('bulkeq-reedcloak', 'Reed Cloak', 'Thin travel mantle. (+2 max stamina)', 'equipment', 'common', 88, '{"slot":"cloak","bonuses":{"max_stamina":2}}'),
  ('bulkeq-clay-anklet-duo', 'Clay Ankle Tags', 'Fired discs. (+1 CON)', 'equipment', 'common', 86, '{"slot":"feet","bonuses":{"constitution":1}}'),
  ('bulkeq-patch-tunic-mini', 'Patchwork Jerkin', 'Stitched layers. (+1 INT +1 STA)', 'equipment', 'common', 95, '{"slot":"chest","bonuses":{"intelligence":1,"max_stamina":1}}'),
  ('bulkeq-ash-wraps', 'Ash Hand Wraps', 'Soot-dyed cloth. (+1 STR +1 INT)', 'equipment', 'common', 98, '{"slot":"hands","bonuses":{"strength":1,"intelligence":1}}'),
  ('bulkeq-bark-buckle', 'Bark Belt Buckle', 'Carved clasp. (+1 CON +1 stamina cap)', 'equipment', 'common', 90, '{"slot":"belt","bonuses":{"constitution":1,"max_stamina":2}}'),
  ('bulkeq-stick-wand', 'Practice Twig', 'Waved for focus drills. (+1 INT)', 'equipment', 'common', 79, '{"slot":"weapon","bonuses":{"intelligence":1}}'),
  ('bulkeq-shell-comb', 'Shell Hair Comb', 'Coastal souvenir. (+1 XP% tasks)', 'equipment', 'common', 94, '{"slot":"head","bonuses":{"xp_bonus_pct":1}}'),
  ('bulkeq-thread-ring', 'Woven Thumb Ring', 'Fiber loop. (+1 gold%)', 'equipment', 'common', 84, '{"slot":"ring","bonuses":{"gold_bonus_pct":1}}'),
  ('bulkeq-hide-greaves-mini', 'Scrap Hide Guards', 'Knee scraps. (+1 STR)', 'equipment', 'common', 87, '{"slot":"legs","bonuses":{"strength":1}}'),
  ('bulkeq-pin-brooch', 'Bone Pin Brooch', 'Lodged on shoulder. (+1 CON)', 'equipment', 'common', 91, '{"slot":"shoulders","bonuses":{"constitution":1}}'),
  ('bulkeq-driftwood-knuckle', 'Driftwood Knuckle', 'Sanded guard knot. (+1 STR +1 STA)', 'equipment', 'common', 96, '{"slot":"hands","bonuses":{"strength":1,"max_stamina":1}}'),
  ('bulkeq-linen-sash-long', 'Linen Traveling Sash', 'Many pockets lore. (+2 STA)', 'equipment', 'common', 93, '{"slot":"waist","bonuses":{"max_stamina":2}}'),
  ('bulkeq-rust-charm-disk', 'Rust Disk Charm', 'Pitted iron luck. (+1 gold%)', 'equipment', 'common', 89, '{"slot":"charm","bonuses":{"gold_bonus_pct":1}}'),
  ('bulkeq-beech-antler-mini', 'Beech Twig Crown', 'Two tiny forks. (+1 INT)', 'equipment', 'common', 83, '{"slot":"head","bonuses":{"intelligence":1}}'),
  ('bulkeq-rope sandals-wrap', 'Rope Wrap Sandals', 'Grip training soles. (+1 CON)', 'equipment', 'common', 81, '{"slot":"feet","bonuses":{"constitution":1}}'),

  -- uncommons
  ('bulkeq-bronze-sun-pin', 'Bronze Sun Pin', 'Warm glint pauldron. (+2 STR)', 'equipment', 'uncommon', 165, '{"slot":"shoulders","bonuses":{"strength":2}}'),
  ('bulkeq-jade-reading-loop', 'Jade Lens Loop', 'Scholar monocle weave. (+2 INT)', 'equipment', 'uncommon', 172, '{"slot":"head","bonuses":{"intelligence":2}}'),
  ('bulkeq-rune-scarf-soft', 'Rune-soft Scarf', 'Embroidered focus. (+1 INT +1 XP%)', 'equipment', 'uncommon', 178, '{"slot":"chest","bonuses":{"intelligence":1,"xp_bonus_pct":1}}'),
  ('bulkeq-wax-seal-band', 'Wax Seal Armlet', '+2 STR + sealed edges.', 'equipment', 'uncommon', 168, '{"slot":"hands","bonuses":{"strength":2}}'),
  ('bulkeq-pewter-loop', 'Pewter Trade Loop', 'Merchant luck. (+2 gold%)', 'equipment', 'uncommon', 175, '{"slot":"charm","bonuses":{"gold_bonus_pct":2}}'),
  ('bulkeq-leather-route-belt', 'Route Leather Belt', 'Travel wards. (+2 CON)', 'equipment', 'uncommon', 170, '{"slot":"belt","bonuses":{"constitution":2}}'),
  ('bulkeq-silverbite-practice', 'Silverbite Practice Blade', 'Dull sparkle edge. (+2 STR)', 'equipment', 'uncommon', 182, '{"slot":"weapon","bonuses":{"strength":2}}'),
  ('bulkeq-weave-cloak-lite', 'Weave-lite Cloak', 'Glides quietly. (+3 max stamina)', 'equipment', 'uncommon', 185, '{"slot":"cloak","bonuses":{"max_stamina":3}}'),
  ('bulkeq-marble-chip-ring', 'Marble Chip Signet', 'Cool palm stone. (+1 INT +1 gold%)', 'equipment', 'uncommon', 178, '{"slot":"ring","bonuses":{"intelligence":1,"gold_bonus_pct":1}}'),
  ('bulkeq-iron-shin-strip', 'Iron Shin Strips', 'Strapped plates. (+2 CON)', 'equipment', 'uncommon', 172, '{"slot":"legs","bonuses":{"constitution":2}}'),
  ('bulkeq-cobalt-wire-hair', 'Cobalt Wire Hairnet', '+2 INT + minor glow.', 'equipment', 'uncommon', 179, '{"slot":"head","bonuses":{"intelligence":2}}'),
  ('bulkeq-hide-claw-glove', 'Hide Claw Glove Pair', '+1 STR +1 CON.', 'equipment', 'uncommon', 174, '{"slot":"hands","bonuses":{"strength":1,"constitution":1}}'),
  ('bulkeq-anchor-chain-charm', 'Anchor Chain Charm', 'Pulls fortunes. (+2 gold%)', 'equipment', 'uncommon', 181, '{"slot":"charm","bonuses":{"gold_bonus_pct":2}}'),
  ('bulkeq-sage-stole-short', 'Sage Short Stole', 'Study sessions. (+2 XP%)', 'equipment', 'uncommon', 188, '{"slot":"chest","bonuses":{"xp_bonus_pct":2}}'),
  ('bulkeq-ember-dust-boots', 'Ember Dust Boots', 'Warm footfall. (+2 max stamina)', 'equipment', 'uncommon', 176, '{"slot":"feet","bonuses":{"max_stamina":2}}'),
  ('bulkeq-phantom-ribbon-cape', 'Phantom Ribbon Cape', '+1 XP% +3 STA.', 'equipment', 'uncommon', 186, '{"slot":"cape","bonuses":{"xp_bonus_pct":1,"max_stamina":3}}'),
  ('bulkeq-grips-of-toil', 'Grips of Toil', '+2 STR + labors pride.', 'equipment', 'uncommon', 173, '{"slot":"hands","bonuses":{"strength":2}}'),
  ('bulkeq-auric-hairpin', 'Auric Crescent Pin', '+2 INT +1 gold%.', 'equipment', 'uncommon', 184, '{"slot":"head","bonuses":{"intelligence":2,"gold_bonus_pct":1}}'),

  -- rare
  ('bulkeq-moonsteel-hair-wire', 'Moonsteel Hair-wire', '+3 INT sharp mind.', 'equipment', 'rare', 348, '{"slot":"head","bonuses":{"intelligence":3}}'),
  ('bulkeq-glacier-spark-blade', 'Glacier Spark Cleaver', 'Cold practice edge. (+3 STR)', 'equipment', 'rare', 352, '{"slot":"weapon","bonuses":{"strength":3}}'),
  ('bulkeq-duskwoven-cloak', 'Duskwoven Cloak', '+3 STA + stealth fold.', 'equipment', 'rare', 362, '{"slot":"cloak","bonuses":{"max_stamina":3}}'),
  ('bulkeq-sunwake-girdle', 'Sunwake Girdle', '+2 CON +8 STA.', 'equipment', 'rare', 378, '{"slot":"waist","bonuses":{"constitution":2,"max_stamina":8}}'),
  ('bulkeq-thornfinger-gloves', 'Thornfinger Gloves', '+2 STR +2 INT.', 'equipment', 'rare', 356, '{"slot":"hands","bonuses":{"strength":2,"intelligence":2}}'),
  ('bulkeq-heartglass-amulet', 'Heartglass Amulet', '+3 gold% echoes.', 'equipment', 'rare', 392, '{"slot":"charm","bonuses":{"gold_bonus_pct":3}}'),
  ('bulkeq-myth-yarn-ring', 'Myth Yarn Ring', '+3 XP% stories.', 'equipment', 'rare', 389, '{"slot":"ring","bonuses":{"xp_bonus_pct":3}}'),
  ('bulkeq-obsidian-disk-mantle', 'Obsidian Disk Mantle', '+3 CON pauldrons.', 'equipment', 'rare', 368, '{"slot":"shoulders","bonuses":{"constitution":3}}'),
  ('bulkeq-crater-plate-boots', 'Crater Plate Boots', '+3 STA stomp.', 'equipment', 'rare', 360, '{"slot":"feet","bonuses":{"max_stamina":3}}'),
  ('bulkeq-ritual-split-robe', 'Ritual Split Robe', '+2 INT +4 XP%.', 'equipment', 'rare', 410, '{"slot":"chest","bonuses":{"intelligence":2,"xp_bonus_pct":4}}'),
  ('bulkeq-nightpull-charm-loop', 'Nightpull Loop Charm', '+3 STA +3 gold%.', 'equipment', 'rare', 404, '{"slot":"charm","bonuses":{"max_stamina":3,"gold_bonus_pct":3}}'),
  ('bulkeq-steelweft-greaves-r', 'Steelweft Greaves', '+4 STR shin guard.', 'equipment', 'rare', 371, '{"slot":"legs","bonuses":{"strength":4}}'),
  ('bulkeq-aurora-halo-band', 'Aurora Halo Band', '+4 INT halo.', 'equipment', 'rare', 396, '{"slot":"head","bonuses":{"intelligence":4}}'),
  ('bulkeq-phasewind-cape-short', 'Phasewind Short Cape', '+5 STA veil.', 'equipment', 'rare', 382, '{"slot":"cape","bonuses":{"max_stamina":5}}'),

  -- epic (shop-available; strengthens forge pool diversity)
  ('bulkeq-echo-drake-collars', 'Echo Drake Twin Collars', '+4 STR dragon echo.', 'equipment', 'epic', 998, '{"slot":"shoulders","bonuses":{"strength":4}}'),
  ('bulkeq-archivist-cowl', 'Archivist Cowl Apex', '+5 INT lore crown.', 'equipment', 'epic', 1050, '{"slot":"head","bonuses":{"intelligence":5}}'),
  ('bulkeq-crucible-wrap-hands-e', 'Crucible Wrap Apex', '+4 STR +3 CON smith.', 'equipment', 'epic', 990, '{"slot":"hands","bonuses":{"strength":4,"constitution":3}}'),
  ('bulkeq-starfall-pendant', 'Starfall Pendant', '+5 gold% bounty.', 'equipment', 'epic', 1180, '{"slot":"charm","bonuses":{"gold_bonus_pct":5}}'),
  ('bulkeq-glassheart-sabatons', 'Glassheart Sabatons', '+10 STA stride.', 'equipment', 'epic', 960, '{"slot":"feet","bonuses":{"max_stamina":10}}'),
  ('bulkeq-voidthread-mantle', 'Voidthread Mantle', '+4 CON shadow cloth.', 'equipment', 'epic', 1095, '{"slot":"chest","bonuses":{"constitution":4}}'),
  ('bulkeq-crownspire-blade-mini', 'Crownspire Tooth Blade', '+5 STR ceremonial.', 'equipment', 'epic', 1140, '{"slot":"weapon","bonuses":{"strength":5}}'),
  ('bulkeq-sigil-ceinture-wide', 'Sigil Wide Ceinture', '+4 INT +14 STA.', 'equipment', 'epic', 1065, '{"slot":"belt","bonuses":{"intelligence":4,"max_stamina":14}}'),

  -- legendary shop capstones
  ('bulkeq-sol-wreathed-monarch', 'Sol Wreathed Diadem', '+6 INT +8 XP% blaze.', 'equipment', 'legendary', 4890, '{"slot":"head","bonuses":{"intelligence":6,"xp_bonus_pct":8}}'),
  ('bulkeq-aeon-chain-reliquary', 'Aeon Chain Reliquary', '+8 gold% etched chain.', 'equipment', 'legendary', 4920, '{"slot":"charm","bonuses":{"gold_bonus_pct":8}}'),
  ('bulkeq-titanrope-belt', 'Titanrope Gird', '+6 STR +20 STA atlas.', 'equipment', 'legendary', 4780, '{"slot":"waist","bonuses":{"strength":6,"max_stamina":20}}'),
  ('bulkeq-zenithbreaker-fang', 'Zenithbreaker Fang', '+10 STR mythical tooth.', 'equipment', 'legendary', 5240, '{"slot":"weapon","bonuses":{"strength":10}}'),

  -- consumables
  ('bulkcon-mist-elixir-s', 'Mist Sip Elixir', 'Tiny stamina sip (+6).', 'consumable', 'common', 58, '{"effect":{"stamina":6}}'),
  ('bulkcon-dew-tonic-m', 'Dew Tonic', 'Refreshing dew (+14 STA).', 'consumable', 'common', 78, '{"effect":{"stamina":14}}'),
  ('bulkcon-riverdraft-vial', 'Riverdraft Vial', 'River rush (+26 STA).', 'consumable', 'uncommon', 112, '{"effect":{"stamina":26}}'),
  ('bulkcon-sunpulse-flask', 'Sunpulse Flask', 'Daylight bloom (+42 STA).', 'consumable', 'rare', 198, '{"effect":{"stamina":42}}'),
  ('bulkcon-moonswell-crystal', 'Moonswell Crystal', 'Rare lunar surge (+72 STA).', 'consumable', 'epic', 420, '{"effect":{"stamina":72}}'),

  ('bulkcon-rose-salve', 'Rose Salve Cloth', '+5 HP comfort.', 'consumable', 'common', 48, '{"effect":{"hp":5}}'),
  ('bulkcon-tea-twilight-leaf', 'Twilight Leaf Tea', '+12 HP steeped.', 'consumable', 'common', 72, '{"effect":{"hp":12}}'),
  ('bulkcon-phoenix-pinfeather-tea', 'Pinfeather Revive Tea', '+28 HP smoky.', 'consumable', 'uncommon', 128, '{"effect":{"hp":28}}'),
  ('bulkcon-dreamfoam-tinct', 'Dreamfoam Tincture', '+55 HP ethereal.', 'consumable', 'rare', 255, '{"effect":{"hp":55}}'),
  ('bulkcon-oracle-balm-jar', 'Oracle Balm Jar', '+108 HP lore.', 'consumable', 'epic', 510, '{"effect":{"hp":108}}'),

  ('bulkcon-double-mist-kit', 'Double Mist Kit', 'Two sips stamina bundle.', 'consumable', 'common', 99, '{"effect":{"stamina":10}}'),
  ('bulkcon-guardian-roll', 'Guardian Meal Roll', 'HP + stamina trail mix vibe.', 'consumable', 'uncommon', 145, '{"effect":{"hp":10,"stamina":10}}'),
  ('bulkcon-monsoon-jar-mini', 'Monsoon Jar Mini', '+32 STA crashing wave.', 'consumable', 'rare', 220, '{"effect":{"stamina":32}}'),

  -- cosmetics / furniture / pets
  ('bulkdec-whisper-mask', 'Whisper Painted Mask', 'Focus ritual face paint.', 'cosmetic', 'uncommon', 130, '{"slot":"mask"}'),
  ('bulkdec-aurora-veils', 'Aurora Thread Veils', 'Shimmers in UI ambience.', 'cosmetic', 'rare', 280, '{"slot":"cloak_cosmetic"}'),
  ('bulkdec-sun-disk-mark', 'Sun Disk Body Mark', 'Solar geometry ink.', 'cosmetic', 'common', 70, '{"slot":"tattoo"}'),
  ('bulkdec-moon-cheek-dash', 'Moon Cheek Dash', 'Quick cosmetic dash.', 'cosmetic', 'common', 65, '{"slot":"face"}'),
  ('bulkdec-crystal-brow-bind', 'Crystal Brow Bind', 'Tiny spark bindi.', 'cosmetic', 'rare', 240, '{"slot":"forehead"}'),
  ('bulkdec-echo-mask-half', 'Half Echo Mask', 'One eye covered mystic.', 'cosmetic', 'epic', 520, '{"slot":"mask"}'),
  ('bulkdec-starfield-nails', 'Starfield Nail Polish', 'Typing glitter.', 'cosmetic', 'uncommon', 115, '{"slot":"hands_cosmetic"}'),
  ('bulkdec-rune-cheek-lines', 'Rune Cheek Lines', 'Subtle wards.', 'cosmetic', 'uncommon', 108, '{"slot":"face"}'),
  ('bulkdec-garden-halo-wire', 'Garden Halo Wire', 'Florals glow.', 'cosmetic', 'rare', 290, '{"slot":"head_cosmetic"}'),
  ('bulkdec-void-eye-liner-kit', 'Void Eye Liner', 'Tiny star trails.', 'cosmetic', 'epic', 480, '{"slot":"eyes"}'),

  ('bulkroom-candle-matrix', 'Candle Matrix Tray', 'Grid of tealights.', 'furniture', 'common', 105, '{"placement":"table"}'),
  ('bulkroom-crystal-geode-seat', 'Geode Meditation Seat', 'Spark studded cushion.', 'furniture', 'uncommon', 215, '{"placement":"seat"}'),
  ('bulkroom-star-chart-drape', 'Star Chart Curtain', 'Celestial map fabric.', 'furniture', 'uncommon', 198, '{"placement":"window"}'),
  ('bulkroom-moss-lantern-trio', 'Moss Lantern Trio', 'Soft green glow stack.', 'furniture', 'common', 92, '{"placement":"shelf"}'),
  ('bulkroom-clockwork-mini-shelf', 'Clockwork Shelf Bracket', 'Gear motif shelf.', 'furniture', 'rare', 342, '{"placement":"wall"}'),
  ('bulkroom-dream-pod-chair', 'Dream Pod Chair', 'Egg chair variant.', 'furniture', 'rare', 380, '{"placement":"seat"}'),
  ('bulkroom-glass-bell-jar-planter', 'Glass Bell Planter', 'Terrarium focus.', 'furniture', 'common', 88, '{"placement":"desk"}'),
  ('bulkroom-ink-well-rack-wall', 'Ink Wall Rack Quills.', 'Study decor.', 'furniture', 'common', 72, '{"placement":"wall"}'),
  ('bulkroom-mirror-scrying-round', 'Scrying Mirror Round', 'Myst framing.', 'furniture', 'epic', 620, '{"placement":"wall_center"}'),
  ('bulkroom-carpet-hex-weave', 'Hex Weave Floor Rug', 'Patterned tile vibe.', 'furniture', 'uncommon', 174, '{"placement":"floor"}'),
  ('bulkroom-shelf-dragon-motif', 'Dragon Motif Shelf', 'Carved claws hold books.', 'furniture', 'epic', 590, '{"placement":"shelf"}'),
  ('bulkroom-lamp-paper-phoenix', 'Paper Phoenix Lantern', 'Folded glow bird.', 'furniture', 'rare', 310, '{"placement":"lamp"}'),

  ('bulkpet-tail-ribbon-kit', 'Tail Ribbon Variety Kit', 'Swap ribbons daily.', 'pet', 'common', 85, '{"cosmetic_tail":true}'),
  ('bulkpet-wing-sticker-set', 'Wing Sticker Glow Set', 'Temporary wing decals.', 'pet', 'uncommon', 142, '{"decal":"wings"}'),
  ('bulkpet-mini-backpack-roll', 'Mini Adventurer Pack', 'Toy satchel cosmetics.', 'pet', 'common', 95, '{"cosmetic_pack":true}'),
  ('bulkpet-antenna-bead-chain', 'Bead Chain Antennas', 'Cute beaded feelers.', 'pet', 'common', 78, '{"cosmetic_antenna":true}'),
  ('bulkpet-mask-kitsune-toy', 'Kitsune Toy Mask', 'Festival flair.', 'pet', 'uncommon', 156, '{"cosmetic_mask":true}'),
  ('bulkpet-floating-orbit-marbles', 'Orbit Marble Familiars', 'Tiny orbiting sprites.', 'pet', 'rare', 298, '{"fx_orbit":true}'),
  ('bulkpet-fin-crystal-mini', 'Crystal Fin Pins', 'Shine on sides.', 'pet', 'uncommon', 148, '{"cosmetic_fins":true}'),
  ('bulkpet-snoot-bandana-pack', 'Snoot Bandana Pack', 'Pattern variety.', 'pet', 'common', 68, '{"cosmetic_bandana":true}'),
  ('bulkpet-crown-micro-quartz', 'Micro Quartz Crown', 'Tiny gemstone crown.', 'pet', 'rare', 320, '{"cosmetic_crown":true}'),
  ('bulkpet-shadow-pelt-dye', 'Shadow Pelt Dye', 'Muted gradient fur tint.', 'pet', 'epic', 545, '{"dye_preset":"shadow"}')
ON CONFLICT (slug) DO UPDATE
SET
  name = EXCLUDED.name,
  description = EXCLUDED.description,
  category = EXCLUDED.category,
  rarity = EXCLUDED.rarity,
  price = EXCLUDED.price,
  metadata = EXCLUDED.metadata,
  is_active = true;
